version: "3.5"

services:
  mall4cloud-redis:
    image: redis:6.2
    container_name: mall4cloud-redis
    restart: always
    ports:
      - 6379:6379

  mall4cloud-minio:
    image: minio/minio:RELEASE.2021-06-17T00-10-46Z
    container_name: mall4cloud-minio
    restart: always
    command: server /data
    ports:
      - 9000:9000
    volumes:
      - ./minio/data:/data
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin123456


  mall4cloud-rocketmq-namesrv:
    image: apache/rocketmq:4.9.4
    container_name: mall4cloud-rocketmq-namesrv
    restart: always
    ports:
      - 9876:9876
    volumes:
      - ./rocketmq/namesrv/logs:/home/rocketmq/logs
      - ./rocketmq/namesrv/store:/home/rocketmq/store
    environment:
      JAVA_OPT_EXT: "-Duser.home=/home/rocketmq -Xms512M -Xmx512M -Xmn128M"
    command: ["sh","mqnamesrv"]
    networks:
      rocketmq:
        aliases:
          - mall4cloud-rocketmq-namesrv

  mall4cloud-rocketmq-broker:
    image: apache/rocketmq:4.9.4
    container_name: mall4cloud-rocketmq-broker
    restart: always
    ports:
      - 10909:10909
      - 10911:10911
    volumes:
      - ./rocketmq/broker/logs:/home/rocketmq/logs
      - ./rocketmq/broker/store:/home/rocketmq/store
      - ./rocketmq/broker/conf/broker.conf:/etc/rocketmq/broker.conf
    environment:
      JAVA_OPT_EXT: "-Duser.home=/home/rocketmq -Xms512M -Xmx512M -Xmn128M -XX:-AssumeMP"
    command: ["sh","mqbroker","-c","/etc/rocketmq/broker.conf","-n","mall4cloud-rocketmq-namesrv:9876","autoCreateTopicEnable=true"]
    depends_on:
      - mall4cloud-rocketmq-namesrv
    networks:
      rocketmq:
        aliases:
          - mall4cloud-rocketmq-broker


#  mall4cloud-rocketmq-dashboard:
#    image: apacherocketmq/rocketmq-dashboard:1.0.0
#    container_name: mall4cloud-rocketmq-dashboard
#    restart: always
#    ports:
#      - 8180:8080
#    environment:
#      JAVA_OPTS: "-Drocketmq.namesrv.addr=mall4cloud-rocketmq-namesrv:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false"
#    depends_on:
#      - mall4cloud-rocketmq-namesrv
#    networks:
#      rocketmq:
#        aliases:
#          - mall4cloud-rocketmq-console


networks:
  rocketmq:
    name: rocketmq
    driver: bridge
