version: "3.5"

services:
  mall4cloud-mysql:
    image: mysql:8.0
    container_name: mall4cloud-mysql
    restart: 'no'
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/initdb:/docker-entrypoint-initdb.d


  mall4cloud-nacos:
    image: nacos/nacos-server:v2.2.0-slim
    container_name: mall4cloud-nacos
    restart: 'no'
    depends_on:
      - mall4cloud-mysql
    ports:
      - 8848:8848
      - 9848:9848
      - 9849:9849
    environment:
      - JVM_XMS=256m
      - JVM_XMX=256m
      - MODE=standalone
      - PREFER_HOST_MODE=hostname
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=123.60.75.135
      - MYSQL_SERVICE_DB_NAME=mall4cloud_nacos
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=root
    volumes:
      - ./nacos/logs:/home/nacos/logs


  mall4cloud-seata:
    image: seataio/seata-server:1.6.1
    container_name: mall4cloud-seata
    restart: 'no'
    depends_on:
      - mall4cloud-mysql
      - mall4cloud-nacos
    ports:
      - 8091:8091
      - 7091:7091
    environment:
      - SEATA_IP=123.60.75.135
    volumes:
      - ./seata/application.yml:/seata-server/resources/application.yml

  mall4cloud-elasticsearch:
    image: elasticsearch:7.17.5
    container_name: mall4cloud-elasticsearch
    restart: 'no'
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch/plugins:/usr/share/elasticsearch/plugins

  mall4cloud-kibana:
    image: kibana:7.17.5
    container_name: mall4cloud-kibana
    restart: 'no'
    ports:
      - 5601:5601
    links:
      - mall4cloud-elasticsearch:elasticsearch
    depends_on:
      - mall4cloud-elasticsearch


  mall4cloud-canal:
    image: canal/canal-server:v1.1.6
    container_name: mall4cloud-canal
    restart: 'no'
    ports:
      - 11111:11111
    volumes:
      - ./canal/conf/example:/home/admin/canal-server/conf/example
      - ./canal/conf/canal.properties:/home/admin/canal-server/conf/canal.properties
      - ./canal/logs:/home/admin/canal-server/logs



